#spring.application.name=GuuPun
spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2.console.enabled: true

encryption:
  key: "1234567890ABCDEF1234567890ABCDEF"  # AES-256の32バイトキー（128ビット）
